server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        # 换成nginx的80端口，做集群
        server-addr: 192.168.75.128:80
management:
  endpoints:
    web:
      exposure:
        include: "*"
